/* Koios, A c++ async runtime library.
 * Copyright (C) 2023  Jeremy Pewterschmidt
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#ifndef KOIOS_COROUTINE_MUTEX_H
#define KOIOS_COROUTINE_MUTEX_H

#include "koios/macros.h"
#include "koios/task_on_the_fly.h"
#include "koios/moodycamel_queue_wrapper.h"
#include "koios/per_consumer_attr.h"
#include "koios/task.h"
#include "toolpex/move_only.h"

#undef BLOCK_SIZE
#include "concurrentqueue/concurrentqueue.h"

#include <mutex>

KOIOS_NAMESPACE_BEG

class mutex;

/*! \brief  The RAII object which holds the ownership of corresponding mutex. 
 *
 *  This type of object should be generated by a `koios::mutex` object.
 */
class unique_lock : public toolpex::move_only
{
private:
    friend class mutex;
    friend class acq_lk_aw;

    unique_lock(mutex& m) noexcept
        : m_mutex{ &m }
    {
    }

public:
    unique_lock() noexcept = default;
    unique_lock(unique_lock&& other) noexcept;
    unique_lock& operator=(unique_lock&& other) noexcept;

    /*! \brief Regain the ownership of the corresponding mutex (asynchronous) */
    task<void> lock();

    /*! \brief Give up the ownership of the corresponding mutex.
     *  
     *  After give up the ownership, you can `lock()`
     *  corresponding the corresponding mutex.
     */
    void unlock() noexcept;

    /*! \brief Automatically release the ownership. */
    ~unique_lock() noexcept { unlock(); }

    bool is_hold() const noexcept { return m_hold; }

private:
    mutex* m_mutex{};
    bool m_hold{ true };
};

class acq_lk_aw : public toolpex::move_only
{
public:
    acq_lk_aw(mutex& mutex) noexcept
        : m_mutex{ mutex }
    {
    }
    
    bool await_ready() const;
    void await_suspend(task_on_the_fly h);
    unique_lock await_resume() noexcept;

private:
    mutex& m_mutex;
};

struct waiting_handle
{
    per_consumer_attr attr;
    task_on_the_fly task;
};

/*! \brief The coroutine mutex object */
class mutex : public toolpex::move_only
{
public:
    /*! \brief  Acquire the ownership of the mutex (asynchronous)
     *
     *  Due to the underlying mutex may throw an exception when lock it, 
     *  We didn't mark this function as noexcept.
     */
    acq_lk_aw acquire() { return { *this }; }

private:
    friend class unique_lock;
    friend class acq_lk_aw;

    // reentrant
    void try_wake_up_next() noexcept;

    /*! \brief  Try to acquire the ownership.
     *
     *  Due to the underlying mutex may throw an exception when lock it, 
     *  We didn't mark this function as noexcept.
     */
    bool hold_this_immediately();
    void add_waiting(task_on_the_fly t);
    void release();
    
    void try_wake_up_next_impl() noexcept;
    bool being_held() const noexcept { return m_holded; }

private:
    moodycamel::ConcurrentQueue<waiting_handle> m_waitings;

    ::std::mutex m_lock;  
    bool m_holded{false};
};

KOIOS_NAMESPACE_END

#endif
